<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Expenditure extends Model
{
    protected $table = "expenditure";
    protected $fillable = [
        'expense_date',
        'expense_sector',
        'project_name',
        'name',
        'type_of_expense',
        'administrative_expense',
        'human_resource',
        'hr_expense_date',
        'equip_expense_date',
        'equip_cost',
        'equip_supplier_name',
        'travel_exp_date',
        'travel_exp_departure',
        'travel_exp_arrirval',
        'travel_exp_mode_of_travel',
        'date_of_material_exp',
        'item',
        'quantity',
        'rate_per_unit',
        'total_cost',
        'remarks',
        'date_of_accommodation_exp',
        'checkin',
        'checkout',
        'no_of_days',
        'date_of_miscellaneous_exp',
        'other',
        'miscellaneous_exp_remarks',
        'miscellaneous_exp_description',
        'amount',
        'section',
        'tds_deduction_percentage',
        'tds_deduction_amount',
        'pan',
        'tds_deduction_date',
        'mode_of_payment',
        'invoice',
        'proof_of_payment',
        'sub_total_amount',
        'advance',
        'net_payment',
        'advance_deposit',
        'type_of_payment',
        'description',
        'hr_amount',
        'hr_section',
        'hr_tds_deduction_percentage',
        'hr_tds_deduction_amount',
        'hr_pan',
        'hr_tds_deduction_date',
        'hr_total_amount',

        'equip_amount',
        'equip_section',
        'equip_tds_deduction_percentage',
        'equip_tds_deduction_amount',
        'equip_pan',
        'equip_tds_deduction_date',
        'equip_total_amount',

        'travel_exp_amount',
        'travel_exp_section',
        'travel_exp_tds_deduction_percentage',
        'travel_exp_tds_deduction_amount',
        'travel_exp_pan',
        'travel_exp_tds_deduction_date',
        'travel_exp_total_amount',

        'material_amount',
        'material_section',
        'material_tds_deduction_percentage',
        'material_tds_deduction_amount',
        'material_pan',
        'material_tds_deduction_date',
        'material_total_amount',

        'accomodation_amount',
        'accomodation_section',
        'accomodation_tds_deduction_percentage',
        'accomodation_tds_deduction_amount',
        'accomodation_pan',
        'accomodation_tds_deduction_date',
        'accomodation_total_amount',

        'miscellaneous_amount',
        'miscellaneous_section',
        'miscellaneous_tds_deduction_percentage',
        'miscellaneous_tds_deduction_amount',
        'miscellaneous_pan',
        'miscellaneous_tds_deduction_date',
        'miscellaneous_total_amount',
    ];
}
